### ISSUE TITLE
Adding new country

### ISSUE THREAD

**Issue by StanislavTichy** [simonpoole/geocontext#1]
Hi there,I am not a coder but translator and don't know how to participace here. I just wanted to add info about my country Czech Republic:

"cz"
        "speed-limits": [
            20 living street and pedestrian zone limit,
            30 common street sign limit inside urban area,
            50 urban area limit for everyone, common speed sign limit outside urban area in dangerous places,
            70 common speed sign limit outside urban area
            80 speed limit for vehicles over 3,5 tonnes everywhere, limit for motorway and highway inside urban area for all vehicles,
            90 limit for vehicles under 3,5 tonnes outside urban area,
            110 limit for motorway,
            130 limit for highway
        ]
 "distance": "metric"
 "left-hand-traffic": false

https://commons.m.wikimedia.org/wiki/File:CZ-IP28b_Nejvyšší_dovolené_rychlosti_(2016_-_verze_2015-07-31).jpg

**Comment by simonpoole** [comment]
I'm on vacation for a couple of days, will add this when I'm back.

**Comment by StanislavTichy** [comment]
For other countries we can use at least https://wiki.openstreetmap.org/wiki/Speed_limits#Country_code.2Fcategory_conversion_table and https://wiki.openstreetmap.org/wiki/Default_speed_limits to export some data

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/geocontext/commit/5fae1d90f7e719d3254249652ca7eaca1ebf044e
