### ISSUE TITLE
Bad JSON coding

### ISSUE THREAD

**Issue by debyos** [simonpoole/geocontext#9]
Hi,
it seems that [I have to learn much on how to code JSON](https://github.com/simonpoole/geocontext/actions/runs/720508651). Could you please correct my [pull request](https://github.com/simonpoole/geocontext/pull/8).
Thanks
Gábor

**Comment by simonpoole** [comment]
You simply need to add commas after the objects :-) Can I push to your PR?

**Comment by debyos** [comment]
Yes, you can push it. Thanks for the teaching! ;-)

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/geocontext/commit/820ea46297d583cbcaa6f8a20fe63ccbff477a37
